### ISSUE TITLE
Problem with Fmax evaluation

### ISSUE THREAD

**Issue by coolmaksat** [ashleyzhou972/CAFA_assessment_tool#8]
Dear Ashley,
I'm trying to compare the our method with CAFA methods and used this tool to compute
Fmax. However, I found that the results do not match slightly for MFO and CCO, and
I get significantly different results for BPO with the same benchmark.
I think there are two reasons for this:

- your version of the Gene Ontology do not match CAFA ontology version which is here https://www.biofunctionprediction.org/cafa/ (Look at Additional Information)
- your evaluation do not consider complete annotations because you split the annotations before propagating them with the ontology structure.

The second reason is significantly affecting BPO annotations because many MFO classes are related to some BPO classes. If you look at *_ancestors_mfo.txt file, you'll find many BPO classes. However, since you are using split leafonly_MFO.txt, leafonly_CCO.txt, leafonly_BPO.txt files in your benchmark, the propagated BPO classes from MFO annotations will not be considered in BPO evaluation and will be counted as False Positives if they are predicted by the method.

To fix this issue the annotations should be merged, propagated and then split into three parts.

**Comment by ashleyzhou972** [comment]
This issue is currently fixed. I have restricted the ancestors to be within the same ontology as the original term, as was the case in CAFA2 evaluations.
